// <auto-generated />
namespace Rationarum_v3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixedAssetAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedAssetAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201512211221585_fixedAssetAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
